#ifndef CONST_H_INCLUDED
#define CONST_H_INCLUDED

#define REVIEW_ID_SIZE 100
#define REVIEW_TEXT 500
#define REVIEW_UPVOTES_SIZE 10
#define REVIEW_APP_VERSION 10
#define REVIEW_POSTED_DATE 20




#endif // CONST_H_INCLUDED
